# Configuration for analysis

# information on serum samples
# serum_info: data/serum_info.csv

# information on neutralization assays against wildtype
neut_config: data/neut_config.yaml

# results directories
plot_outdir: results/plots